// type Fetch PRODUCT
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_MORE_PRODUCT = 'FETCH_MORE_PRODUCT';

// redux-saga PRODUCT
export const FETCH_PRODUCT_SUCCEEDED = 'FETCH_PRODUCT_SUCCEEDED';
export const FETCH_MORE_PRODUCT_SUCCEEDED = 'FETCH_MORE_PRODUCT_SUCCEEDED';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';